### ISSUE TITLE
Show dots that represent items inside closed sections in style panel

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1262]
Split from #1100

<img width="246" alt="Screenshot 2023-03-17 at 15 30 06" src="https://user-images.githubusercontent.com/825702/225892761-9069986b-1e40-4348-9c67-8dfbdaafcf17.png">

@taylornowotny @kof some questions:

 - Do we want the dots only for sections like "Backgrounds" where you add/remove items, or for all sections?
 - Do we want to show `preset` as a dot? Currently in Figma color for the `preset` dot is not defined.

**Comment by kof** [comment]
Any section could have defined styles, this is what the dots are showing

**Comment by kof** [comment]
The problem we are solving is seeing right away, quickly where are values defined, otherwise you have to open each section to find out

**Comment by kof** [comment]
This is actually super important, can't comfortably use the style panel without it

**Comment by taylornowotny** [comment]
To answer your question @rpominov while reiterating what @kof said,

yes we want the dots to show on all sections when applicable and

yes it's intentional that there is no preset dot. The point is to help the user keep track of styles that they have applied, which is not the case with preset styles.
