### ISSUE TITLE
Labels in Section Titles

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1271]
Some sections may represent a single CSS property. In these cases, we want to have all the functionality of the Label component (colors, hovers, tooltips) within the Section Title.

The **Section Title** component is now using a nested **Label** component for the title text AND the **Label** component now has "Section Title" variants. The new Label variants are only different in that they are using text style: "Title".

On most sections this label will remain in the default color but _when the section title represents a single CSS property,_ the label may get a preset/local/remote color. For example, clicking the "+" in the Background Section Title adds a background AND changes Label color to "local" to indicate that a background has been set. See the Background section docs for more.

New docs on the **Section Title** component:
<img width="405" alt="Screenshot 2023-03-20 at 7 48 25 PM" src="https://user-images.githubusercontent.com/86495896/226507063-fae2bbcd-8ae1-4cc5-8836-c52cfa6a0365.png">

New variants of the Label component:
<img width="556" alt="Screenshot 2023-03-20 at 8 01 59 PM" src="https://user-images.githubusercontent.com/86495896/226508456-236b2069-9650-4753-8570-c54d90452dbc.png">

Let me know if I can assist in any way!

**Comment by rpominov** [comment]
I have couple questions.

How do we want the reset popover to behave? Currently we show it on a click on a label.

<img width="231" alt="Screenshot 2023-03-21 at 14 33 37" src="https://user-images.githubusercontent.com/825702/226581317-0c3a4176-d496-436a-89fb-37789428a5e8.png">

- When section is closed, should click on the label open the popover?
- When section is open, I assume we want the click to open the popover. But is it ok, that user won't be able to close the section by clicking on the label?

Also, I think we need a focus state for Label in general since it's clickable.

**Comment by taylornowotny** [comment]
We want all Label functionality to be the same here. So yes, it should show the popover on click when open. When section is closed the label is not visible so clicking anywhere on the Title should just open the section.

The UX of Labels is going to be looked at when I redesign tooltips. At that time I'll consider showing the popover on hover rather than on click and also adding a focus state.

**Comment by rpominov** [comment]
Sound good. But what should I do in meantime with the focus? Options the I see:

- don't allow to focus it via keyboard (reset will be inaccessible using keyboard)
- use hover state for focus as well

**Comment by taylornowotny** [comment]
For a focus state you can give it a 2px border, radius 3px, color: border.focus
