### ISSUE TITLE
Set loading state when opening project from dashboard

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1334]
When user hits on a project thumbnail, remix router starts loading builder, but as things can be slower user doesn't see any reaction on that click for a while, so we need some spinner, because this will lead to frustration otherwise.

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=1111%3A33116&t=hSHfAVHhhsnKRL43-1

**Comment by kof** [comment]
![image](https://user-images.githubusercontent.com/52824/235642895-708919d2-9b5e-4b3b-9d2f-dda5ffecfedd.png)


https://user-images.githubusercontent.com/52824/235642946-3c024801-6c81-4b37-bb5d-e59368080479.mp4

**Comment by kof** [comment]
@markxtang please attach the original source file for the indicator

**Comment by kof** [comment]
I would definitely prefer an svg based loading indicator, svg can animate

**Comment by kof** [comment]
But given that spinner design I am not sure this can be done in that form as svg easily, so we eventually need both - a design that works as svg and an implementation using svg that animates

**Comment by kof** [comment]
here is a gradient we use for cascade indication: `linear-gradient(90deg, #bd2fdb 0%, #4a4efa 100%)` maybe we could use it and animate it

**Comment by nettohadi** [comment]
[Here](https://codepen.io/hadi_sy/pen/abRLRvG) is a little experiment that I did to create an SVG loading indicator. This is my first time doing it so it doesn't look exactly like the webm version. What do you think @markxtang?

**Comment by nettohadi** [comment]
@markxtang - I heard you're planning to create the SVG version yourself. So I think I will leave it to you.

**Comment by nettohadi** [comment]
@markxtang & @kof - I can't find any information on the loading indicator or the light dan dark overlay in the above figma link. I need informations such as size, color, or the opacity of the overlay.

**Comment by kof** [comment]
@nettohadi me neither, @markxtang seems to have done the overlays somewhere else @markxtang can you add them there?

**Comment by markxtang** [comment]
@nettohadi Your codepen looks 90% done, so you should finish it.

**Resources**
I added the overlay information in the docs. The URL is here: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=1477%3A47036&t=WuTvmzOR14WRdR4E-1

I added 4 color tokens for the spinner (addition to Tokens Studio pending PR), which are the 4 primary brand colors (to my eye, it looks like you're already using the correct colors in your WIP, but it's there in case you need it). I'm not providing any gradient tokens because I don't know how you're animating your gradient in SVG, and I know Tokens Studio doesn't support gradients anyway.

**Feedback**
My biggest feedback is the line shrinks into a dot at random parts of the circle each time. It should always shrink into a dot at the 12 o' clock position (see screenshot)
![image](https://user-images.githubusercontent.com/122043657/236574039-cebc8fe8-396e-475a-bfb8-93ed207ea420.png)

Apart from that the gradient transitions seem a bit abrupt. It doesn't feel so smooth to me. I know animating gradients in SVG isn't as easy as in After Effects, so anything you can do to make it smoother would be very appreciated.

Lastly, here's a reference mp4 of what I think it should look like (it's a bit different from the WebMs provided earlier because those were designed to live on a dark background. For the light background, I removed some glow effects).
https://user-images.githubusercontent.com/122043657/236574785-726d3a00-8688-41da-89c0-a83489797ec5.mp4

**Comment by kof** [comment]
@nettohadi once https://github.com/webstudio-is/webstudio-builder/pull/1581 is merged, those colors will be available under theme.colors.brand...

**Comment by nettohadi** [comment]
I will replace all the brand colors in the SVG with the ones from the design tokens.

**Comment by nettohadi** [comment]
I believe It may take awhile if I do the animation manually, I honestly don't know what I am doing with the SVG, it's been pure random attempt. 

So I decided to try the https://app.svgator.com/ and have spent a couple of hours trying to figure out how to use it. When I try to export the animation, it told me to pay if I want to export the whole thing 😄.

**Comment by nettohadi** [comment]
Anyway, other than the SVG animation, I believe I finished working on the [PR](https://github.com/webstudio-is/webstudio-builder/pull/1579). @kof, could help review my latest commits? Let me know if I missed anything.

**Comment by markxtang** [comment]
#### The way I see it, there are 3 options: 
1. Let @nettohadi finish the animation as planned (either using direct code or SVG Gator). Worse come to worse, just pay for a month, export and cancel the membership. I think that should be a negligible cost compared to the labor costs. I can provide a video walkthrough of my After Effects keyframes if that helps the SVG animation process.

2. I take this over and do it in SVG Gator. Probably not as efficient as option 1, but I'm fairly confident I can get it done.

3. I come up with a simpler concept and handover to @nettohadi. This to me is the most inefficient option as I'll need some time to rethink the spinner, then handover/explain, then review, etc.

#### Here are 2 additional options I can think of:
4. Use the revised WebM file I passed to @kof: 
[Spinner_128px 2.webm](https://github.com/webstudio-is/webstudio-builder/assets/122043657/9b4b6c57-9882-466b-b469-5b8e226aaa9d)

5. Find some stock SVG animated spinner online and buy it.

**Comment by markxtang** [comment]
Try this one out @kof @nettohadi 
![Spinner_Animation](https://github.com/webstudio-is/webstudio-builder/assets/122043657/6af87b2c-66e0-4962-86e3-86bea4214609)

**Comment by kof** [comment]
@markxtang how did you make it?

**Comment by markxtang** [comment]
> @markxtang how did you make it?

[SVGator](https://app.svgator.com/)

**Comment by kof** [comment]
@markxtang 2kb is great size, animation is not super interesting, but it would do if you don't have better ideas

**Comment by kof** [comment]
We should keep it as svg file, because this makes it easier to update and just use it inside the component

**Comment by nettohadi** [comment]
@markxtang could you give me the svg file?

**Comment by markxtang** [comment]
It's in my last post, just right click and "save image as"

**Comment by nettohadi** [comment]
@kof where should I put the svg file? In public directory and reference it by url in the component? Or import it and use it as a component?

**Comment by nettohadi** [comment]
> It's in my last post, just right click and "save image as"

Right, I didn't realize that it is already an SVG file 😁. Great work @markxtang.

**Comment by kof** [comment]
@nettohadi I would import it as a string, but @TrySound is the expert on svg
