### ISSUE TITLE
Updating icons in the Add Panel and Navigator.

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1362]
Here's a link to the list in Figma, where the icons can be copied from. Please let me know if you need me to export them as SVGs: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=3755%3A47740&t=eqmtE0MwLo7ozxYi-1

![image](https://user-images.githubusercontent.com/122043657/229630596-90376689-0a4e-43d9-8415-59574fd2e7cf.png)

**Comment by taylornowotny** [comment]
Note: The icon used for the Navigator item should be the same as the element label on the canvas.

<img width="75" alt="Screenshot 2023-04-17 at 10 45 29 AM" src="https://user-images.githubusercontent.com/86495896/232567627-6973cd4e-e201-4236-b94b-8a0d98eba4a0.png">

**Comment by kof** [comment]
Components can't have 2 icons, we need to have one for technical reasons.

**Comment by taylornowotny** [comment]
> Components can't have 2 icons, we need to have one for technical reasons.

Are you suggesting that we can't use a different icon in the Add panel vs the Navigator?

**Comment by kof** [comment]
> Are you suggesting that we can't use a different icon in the Add panel vs the Navigator?


yes, icon is part of a component, component can only provide one icon

**Comment by taylornowotny** [comment]
Surely there is a way to show a different icon in the Add panel card. It's just cosmetic there, in all other cases we use the normal 16px icon.

**Comment by kof** [comment]
@taylornowotny I guess I didn't realize it earlier. The problem is here that components are part of sdk and sdk can be replaced by the user, if we add another icon, it means we have to extend the meta api to support 2 icons. Technically its not impossible but it is seriously undesirable to complicate that api with this.

**Comment by kof** [comment]
@taylornowotny I would say lets keep an eye on this problem for later stages, its not a definitive "no", its "not now".

**Comment by taylornowotny** [comment]
@kof Understood.

I've updated the linked page in the design. I guess currently the Add panel is scaling up the 16px icons to 22px? Let's keep that approach for now.

<img width="799" alt="Screenshot 2023-04-18 at 9 06 39 AM" src="https://user-images.githubusercontent.com/86495896/232837134-d94c0c86-6631-4572-ac92-b6d9a65f932b.png">

This issue is still very important to get done before we share more screenshots or video becuase it has a big effect on the appearance of the UI.

**Comment by taylornowotny** [comment]
It is still very important to update prod with these icons from the design becuase it has a significant effect on the appearance and consistency of our UI.

**Comment by kof** [comment]
we can also scale down 22px icons to 16 if that works better for design

**Comment by taylornowotny** [comment]
No, stick with the 16px icons and scale them up. Otherwise the lines in the 16px icons would be inconsistent with other 16px icons in the UI.
