### ISSUE TITLE
RTE link styling regression

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1380]
When editing RTE, link suddenly gets different styles than after exiting editing mode

https://user-images.githubusercontent.com/52824/230070052-df32dec5-b3a1-460d-a41d-dde94eb08e70.mp4

**Comment by TrySound** [comment]
Something to do with default props. @rpominov how do you think better handle it?

**Comment by rpominov** [comment]
Seems like RTE always sets `href=""`, but in view mode `Link` may have no `href` if it isn't set in props panel. Having a `href` changes styles.

Two ways to fix:

1. In our `Link` component, use `""` if not set in props. Downside: users won't be able to achieve no-href behaviour, although unlikely anyone will want that. 
2. In RTE mode, use `href` from props, instead of always setting to `""`

**Comment by kof** [comment]
@rpominov first approach seems fine, achieving a link without href shouldn't be possible after all, since its not even valid

**Comment by rpominov** [comment]
I'll fix in the my current PR
