### ISSUE TITLE
Navigator: Selecting a child element on canvas should open parent item so it's visible in Navigator tree

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1479]
Currently if a parent element is closed/collapsed in the Navigator and the child is selected on the canvas, the parent stays closed and the user has no indication of where the selected item is located in the tree. There can be many parent elements in the page and the user wouldn't know which one contains the selected element until they manually open every single one.

- [ ] When a child element is selected on the canvas, all parents of that element should open/expand in the Navigator so that the currently selected element is always visible in the Navigator.

**Comment by rpominov** [comment]
This seem to already work as expected, or am I missing something?


https://user-images.githubusercontent.com/825702/233299302-341d8c6b-e35d-4063-b4e7-b2b7cee14863.mov

**Comment by rpominov** [comment]
The only potentially wrong behaviour I've noticed is when user manually closes parent of the selected element, and then clicks on canvas again we don't expand tree because selected element does not change the entire time:

https://user-images.githubusercontent.com/825702/233300965-0660bdd5-b246-4db4-91a9-fcb945dd3b89.mov

Maybe in this scenario, when user closes a parent that contains the selected item, we should make the parent selected instead of keeping the now hidden child selected.

**Comment by taylornowotny** [comment]
Looks good, thank you! I must have been encountering a bug. Not sure how to recreate so I'll close this
