### ISSUE TITLE
Update Text Link name

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1677]
<img width="78" alt="Screenshot 2023-05-25 at 12 13 14 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/70cdfeef-7916-45d9-8a9c-75f66c0d13e0">

This component should be named: Text Link, not Link Text

Because this component is not the text of a link, but rather a link that is text. 

Thank you

**Comment by TrySound** [comment]
Same with Link Block?

**Comment by kof** [comment]
webflow has Block Link and Link Text ... this stuff is full of inconsistencies

**Comment by taylornowotny** [comment]
Let's talk a little more @TrySound @kof - I'd like our names to be consistent. 

What is the meaning of the word "block" in this context? Is this a CSS term or something that webflow made up?

Would it make more sense to say "Box"? - Text Box, Link Box, Text Link

Text Link is better than Link Text, but the other names can make sense both ways.

**Comment by kof** [comment]
It is very possible that webflow is using "Block" for no semantic reason rather than similar than "Box", I just opened this https://university.webflow.com/lesson/div-block 

and saw that the very first sentence is extremely incompetent "A Div block is the most basic and versatile element used when building a website. Buttons, Containers, and Sections are all Div blocks with certain extra properties. "

specifically A div block as a button is a huge huge facepalm.

So they have probably called it for the wrong reason. Real semantics can be probably found around display: block, being a block element, as in block-level content https://developer.mozilla.org/en-US/docs/Glossary/Block-level_content

**Comment by kof** [comment]
I think grammar wise "Link Block" is like "Link Box" semantically, but "Block Link" is more like block level element link

**Comment by TrySound** [comment]
Why Box is not Block? Kinda interesting that Block is often used as a component to build something bigger.

**Comment by kof** [comment]
I think Link Box and Text Box sounds weird. I think we should use "Block" specifically as block-level element semantics and only when the default isn't already block.

1. anchor/link is by default inline, so Block Link makes sense
2. Text is generally unknown component since there is no Text element in html, we are using a div by default which is block-level. I don't see a huge benefit to call it Block Text, since it can be just Text and I don't think it's confusing 
3. Text Link seems like just a Link, there is nothing Text link adds semantically to make it more clear.

**Comment by kof** [comment]
So my version is:
Block Link
Link
Text

**Comment by taylornowotny** [comment]
Text Link
Block Link
Text

?

**Comment by taylornowotny** [comment]
<img width="204" alt="Screenshot 2023-05-30 at 11 39 43 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/0b68070c-3bf7-451f-b82b-f7c360ebcfd4">
This looks really good to me

**Comment by kof** [comment]
I still find Text link weird, because Link is text by default

**Comment by kof** [comment]
> Just "Link" is not clear enough that this is text-only and you can't nest things inside of it. We need to call it something like "Text Link" so that it's clearly distinguishable from "Block Link".

I just realized that you are right, normal link would be Link but it has artificial constraint we added which is only text link, yes that makes sense now

**Comment by kof** [comment]
Lets go with your proposal and lets check if there are other things we need to rename in the same step.

**Comment by taylornowotny** [comment]
I checked and it looks good to my perspective but of course let me know if you want to suggest renaming anything else.

Design is already updated with new names

**Comment by TrySound** [comment]
Box -> Block? Block Link is basically same but link.

**Comment by taylornowotny** [comment]
I like Block over Box. Reminds of Lego.

**Comment by kof** [comment]
Box is an invented term that has no standard semantics. Block is block level element according to the w3c spec, we just need to use it where it applies and not just randomly like webflow

**Comment by kof** [comment]
Box currently based on the tags in the serlection is probably all block level elements, but then again, I haven't seen anyone using "Block" standalone as a replacement for Box.

Even Box as a term is questionable, I was contemplating about it a lot. It would be closer to HTML to call it a Div, but with the tag selectable over props, Div will have to turn into whatever else and we would have to also change it's component name like webflow does when this happens.

We are displaying a label, which comes from the meta declaration and stays the same for the component, tag is kinda changing without affecting the label. We would need to make label dynamic, not static over meta and replace it when tag changes. 

@TrySound correct me if I am wrong but I think it would be non-trivial to do

**Comment by kof** [comment]
Hmm I think maybe we got off wrong with how we turn div into section etc in the first place. What we actually do right now is a polymorphic component - it can change the underlying html element based on props.

Polymorphic components are generally evil. 

What we could be doing instead is converting from Div to Section component. Effectively fully replacing a component instead of passing a tag prop.

To do this we need a place to convert and a list of components for each component we think it would make sense to convert to.

I think this is a generally highly requested functionality because there are cases where you actually need to convert from one to another.

E.g. webflow has on link block context menu "convert to div block".
One gotcha with conversion though is that it's not always possible to apply the same props.

E.g. a Link can have a href prop, when you convert it to div, it won't have it any more.

**Comment by taylornowotny** [comment]
It doesn’t need to be every component, but yes there are some cases where
we want to swap components with a menu. In addition to your examples
there’s the Heading component that we want to switch between all heading
levels and change the icon accordingly.

But I don’t quite understand why that means we need to rename Box to Div
and eliminate the Tag selection.

To my designer brain it makes sense to call it Block bc it’s a block-level
component meant to be used for building - like Lego. That connection is
really nice.

Blocks can be Divs by default and use can change the semantic tag to
something like section. If we remove this, users are going to look for it.

Maybe I just didn’t fully understand your explanation but is the above a
reasonable approach? That’s the option that seems best to me from a UX
standpoint

**Comment by taylornowotny** [comment]
To clarify, I’m suggesting:

Box ➡️ Block
Keep tag property
Build the ability to swap components - but this isn’t really necessary for
most components, only a few.

**Comment by kof** [comment]
@taylornowotny ability to select tag instead of changing component has deep complications if the tag you are selecting has different properties.

E.g. Div and Anchor and not directly interchangeable as Div has not href.

Between Div, Section, Article and others - need to check, there might be differences, not sure. If there are, changing them over tag creates this problem eventually.

**Comment by taylornowotny** [comment]
Yea I'm imagining that the tags can only be switched when it doesn't change the properties, like heading levels and semantic tags like swapping <div> with <section> or <nav>.
- but if we can change the icon when the tag is changed that would be super cool! It would help the use identify the tag quickly from the navigator, eg. seeing the heading level without having to select the heading first then look in the properties to see it. I've heard feedback that people use Webflow's section element only because it has a different icon than a div and that helps them organize their Navigator.

In addition to the tag stuff it would be great to swap between certain components, like Block and Block Link + Text and Text Link. Those are the only cases I can think of so it might be overkill to think about enabling this for all components.

**Comment by kof** [comment]
> but if we can change the icon when the tag is changed that would be super cool!

Icon belongs to component, when we change tag, its the same component but different tag inside. We would need to come up with complex logic to do that if we keep the tag thing.

If we swap out component - it will automatically have the icon

**Comment by kof** [comment]
> it might be overkill to think about enabling this for all components.

Technically for implementation it's only the difference between listing all components and listing specific components. So kinda the the same if we just render them all, but if we have too many of them to fit, it would require search

**Comment by taylornowotny** [comment]
The icon changing when the tag changes is important so let's do what we need to do to make that happen. That's the thing I care about most in this discussion. Saves users lots of time & attention over the course of a project. I know becuase Webflow changes the icon for heading levels and I find that very helpful.

**Comment by kof** [comment]
Doing this renaming now:
Text Link
Block Link
Text
