### ISSUE TITLE
Add a "Preset = True" state to the Radio Button component

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1796]
We need a "Preset=True" state for the Radio Button component in order to have it checked by default on some settings. This need is related to [Issue 1797](https://github.com/webstudio-is/webstudio-builder/issues/1797)

Here's the Radio button component in the [Library Figma](https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=1794%3A5804&t=z7q4qJuAG7KMLSxf-1)

![image](https://github.com/webstudio-is/webstudio-builder/assets/122043657/35d1fc38-7a02-4b1f-8306-b14760a9c136)

**Comment by kof** [comment]
Hmmm, seems tricky for the user to know the difference between preset and set, so the user is supposed to click on a button with preset state and it would change the state to set? 

I think this won't work ... also I don't know why we need to solve #1797 by introducing another state instead of selecting the value that we are supposed to already have set to "none" by default in that particular case

**Comment by taylornowotny** [comment]
It was a style thing, mostly. It's no problem to use the existing checked state.
