### ISSUE TITLE
Incomplete Label in Radix Tooltip Properties.

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio-builder#2047]
Same issue as reported earlier with Name and Vimeo Properties

![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/4057c5a8-00b1-4977-80b1-d55b995e485e)

**Comment by kof** [comment]
@istarkov can we reword these to fit?

**Comment by istarkov** [comment]
This is automatic naming the property itself is huge

**Comment by istarkov** [comment]
We are having this on constant basis with a lot of controls, roght panel is tooo narrow to fit various controls

**Comment by kof** [comment]
@taylornowotny what can we do?

**Comment by kof** [comment]
We could remap the names, e.g. use names that are shorter in the builder but map them to the real once (I believe we even have ability to define a label from meta so the property name is not used) ... but this raises a bunch of other problems:

If code properties and labels it will lead to confusion between designers and developers, since developers might know the code property and designers the name in the panel. Not only can this cause confusion, but it will make communication between designers and developers hard.

Ideal situation is the name stays the same and yet it sometimes can be long.
