### ISSUE TITLE
Token based sharing link with permissions

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#548]
- [ ] We need to be able to share a project with different users with different permissions, for now 3:
  - view - can use the designer, but changes aren't saved, it's just for trying things out without accidentally modifying project
  - design - changes from the design panel will be saved
  - edit content - content changes will be saved
- [ ] A token has to decide what types of permissions the link gets
- [ ] The same token will be used in the CLI
- [ ] stop using project id like a token, currently it's basically the only secret that gives anyone editing access to any site

Notion has a good example for sharing dialog
<img width="476" alt="Screenshot 2022-11-30 at 13 20 09" src="https://user-images.githubusercontent.com/52824/204807325-94d2ac7f-9072-4823-a4d3-f57576bff6d0.png">

**Comment by kof** [comment]
@taylornowotny what part of it do you think is absolutely necessary for the beta launch and what can be done later?

**Comment by kof** [comment]
Honestly for now, I would just let it be a single mode that allows editing everything and a preview mode that is basically the site, without designer, but the state is the latest, no need to be published.

**Comment by kof** [comment]
Just found this issue we already had before, we need to close it, but lets define what needs to be done now for beta and merge them https://github.com/webstudio-is/webstudio-designer/issues/227

**Comment by istarkov** [comment]
- [x] - Add `trpc-interface` package, depending on ENV variables it uses or the local TRPC server or any remote. The local server is used through `callerLink`, which allows calling local implementation directly using `Router.createCaller`. 

- [x] - Write our permission model using ORY permission language

- [x] - TRPC server created at SAAS. Instead of local, it will communicate with ORY permission system.

- [ ] - Clone project through login step issue #790 

- [ ] - Restrict edit/create operations using `userId` `projectId` for the Project and Build, sync projectId, userId with ORY permission system at SAAS

- [ ] - Add projectId field to Tree ref #742 and restrict edit operations on a tree using `userId` `projectId`

- [ ] - Add permission tokens to allow viewing/previewing projects on Canvas. i.e. `?mode=preview` `?mode=edit` both has DB access

- [ ] - Add read permissions checks for Project data read through `userId`, `projectId` AND `token`, `projectId`

**Comment by kof** [comment]
## Link in with view permission

- [ ] When user comes from a link with 'view' permission  we should show the designer initially in "preview" mode (the eye icon). 
- [ ] User should be able to use everything, but we don't send any patches to the server, we just apply things on the canvas without saving them
- [ ] We should have some kind of hint on top that tells you are in view mode and changes won't be saved, to prevent confusion

## Link in with edit permission

- [ ] Again full designer, but starts with a normal view (not preview). 
- [ ] Can do everything, but only content changes will be saved: text edits, and assets uploads.
- [ ] Also some kind of hint on your saving abilities

## Link with build permission

- [ ] Can't delete the project

**Comment by kof** [comment]
Closing, seems done, except content editor permissions
