### ISSUE TITLE
Normalize tree data

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio-builder#696]
Currently we store denormalized tree data in db as json text. This makes postgres useless when dealing with json.

To solve this we can normalize all data and store as array with flat (more or less) objects.

To simplify updates and querying we can colocate all data in single table while split into separate columns.

JSON data stores as text may bloat db very fast. Postgres jsonb is more optimal binary representation. It also supports indexing, which can be a significant advantage.

Postgres json has a lot of builtin utilities

https://www.postgresql.org/docs/15/functions-json.html

Prisma supports json as well

https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields

I propose the following Tree table structure

id: string

instances: jsonb
Array<{ type, id, component, children }>

styles: jsonb
Array<{ breakpointId, instanceId, type, value }>

props: jsonb
Array<{ instanceId, type, name, value, required }>

**Comment by kof** [comment]
1. We need to figure out how to use jsonp without loosing multi-database abstraction from prisma (if that's even possible). We haven't decided yet if we need/want sqllite and prisma doesn't have jsonp for sqllite, so we would have to write raw queries for it

2. We need to fully understand how we are going to implement conflict resolution with offline sync, because depending on that we may need a different solution or even a separate database for these things. It seems that we are going to need an entire tree when we apply patches, so we would either have to do crdt on a database level or store the entire json somewhere in memory or otherwise have some kind of low-latency key-value storage that would quickly give us the full tree.

**Comment by TrySound** [comment]
jsonB is binary json format to store in sql. Nothing more. It has support for direct updates without parsing json in js runtime. So it's not really a transport protocol, just builtin json manipulation on db side.

**Comment by TrySound** [comment]
And looks like sqlite supports json as well though with a little different api
https://www.sqlite.org/json1.html

**Comment by kof** [comment]
@TrySound both of your statements are correct but none has addressed the problems I mentioned

**Comment by TrySound** [comment]
> We need to figure out how to use jsonp without loosing multi-database abstraction from prisma

If we normalize whole data, updating will be the least problem, in worst case we can parse json on server as now

>  It seems that we are going to need an entire tree when we apply patches

It's easier to change normalized tree
