### ISSUE TITLE
Forms UX

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#84]
Users need to be able to control forms through an intuitive UX. Currently we can add a from to a page in Webstudio but users also need to be able to:

- add form field labels
- add & style placeholder text
- control form submission data
- style success, waiting, and error states
- style a field focus state
- customize inputs (multiple fields, radio & checkbox input, dropdown select)
- add recaptcha (after beta)

and on top of that, the html of the form needs to follow [accessibility best practices](https://www.w3.org/WAI/tutorials/forms/).

Webflow handles this with a 'form block' element in which you can add multiple types of fields:
<img width="248" alt="Screen Shot 2022-06-24 at 10 31 09 AM" src="https://user-images.githubusercontent.com/86495896/175612854-2b7cd2a0-d313-4de6-923a-25d60cb505cd.png">

And additionally this menu appears in the settings tab:
<img width="241" alt="Screen Shot 2022-06-24 at 10 33 55 AM" src="https://user-images.githubusercontent.com/86495896/175612974-64b790f4-0b1d-4ad5-89cc-55afa32eb11d.png">
Notice the toggle to change the state from Normal to Success to Error so those states can be styled and customized.

**Comment by rpominov** [comment]
Details discussed on a call regarding the first iteration of forms:

When form is submitted, a email will be send to the owner of the site. Switch between normal/success/error states while in builder will be accomplished with a prop.

- [ ] Add the remaining components: checkbox, radio, ...
- [ ] Check that meta has all the useful states for each form component, including form itself 
- [ ] We move Form component to custom components and rename to RemixForm
- [ ] We add action for all forms and we identify which form is being submitted automatically
- [ ] We handle success and error responses and show SuccessMessage and ErrorMessage components
- [ ] Consider having one component FormMessage instead of ErrorMessage and SuccessMessage, then use status="success"|"error"
- [ ] Get the user email (signup email) from data directly
- [ ] Switch between form states happens over props (already implemented)
- [ ] Create mailer package, use mailchannels api, format the email

**Comment by rpominov** [comment]
Another to-do (copied from https://github.com/webstudio-is/webstudio-builder/pull/1525#issuecomment-1532138860):

- [ ] We can do a lot better on the inputs naming. Let's eliminate the word "field":

current: Radio Button Field -> Radio Button -> Text Block
better: Radio -> Radio Input -> Radio Label

current: Checkbox Field -> Checkbox -> Text Block
better: Checkbox -> Checkbox Input -> Checkbox Label

current: Text Field
better: Text Input

**Comment by rpominov** [comment]
- [ ] Move Button back to forms section
