### ISSUE TITLE
Backgrounds section redesign

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#877]
https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=2440%3A48041

What's left:

- [x] - Use + in the title instead of "Add background" button
- [x] - Focus should work inside layer items using arrows (left/right)
- [x] - Between layers using (top/down)
- [x] - Label colors should be moved somewhere outside of Layer items
- [x] - Fix theme.spacing, do not use px values

**Comment by istarkov** [comment]
# Steps to implement.


## Implement background panel 

- [ ] - Done

<img width="126" alt="image" src="https://user-images.githubusercontent.com/5077042/220930435-6d50c86a-533f-4530-97f6-95adeb4b4f8e.png">

Initially, with "Add background" button, there is no drag/reorder action and hide icon.

Add a floating panel and put inside it the existing background panel section.

## Implement  Floating panel

- [ ] - Done

<img width="121" alt="image" src="https://user-images.githubusercontent.com/5077042/220933797-36875e65-1679-4507-bb43-1567319b7ff5.png">

Omitting position control.

<img width="53" alt="image" src="https://user-images.githubusercontent.com/5077042/220934031-56ab6d87-432f-4421-9952-23e4ef747bda.png">

Code control doesn't parse or do anything with inserted gradient and uses it as is.

## Parse code control at linear gradient section.

- [ ] - Done

Light parsing just extracts gradients without full css `background` parsing.


## Last steps

- [ ] - Add position control.
<img width="53" alt="image" src="https://user-images.githubusercontent.com/5077042/220934031-56ab6d87-432f-4421-9952-23e4ef747bda.png">

- [ ] - Use `+` in the title instead of "Add background" button
- [ ] - Add drag/reordering for the background panel
- [ ] - Add hide icon.
- [ ] - Probably make better parsing of gradient code section i.e. full css background parse.

**Comment by taylornowotny** [comment]
Docs finished! A lot has changed since yesterday so please inspect everything carefully.

The background-color property is now a permanent control, rather than a list item, in response to your feedback.

The position control will be a separate issue. This is a new component and requires some explanation.

Added backgrounds are **CSS Value List Item** component #1118. These will be used again in other sections.

Please let me know if I can assist in any way.

**Comment by taylornowotny** [comment]
Blend Mode - this is a good addition, but please capitalize "Mode". We use Title Case on labels.

I will update the design of this section so that all backgrounds except color are grouped within a single label, per @istarkov feedback

**Comment by taylornowotny** [comment]
Please make sure the text on the toggle group is using the **Labels - Title Case** text style.

**Comment by taylornowotny** [comment]
The height and width properties should be Inputs with unit menus. Currently there is a keyword select but no units. You can copy the height and width properties from the Size section to use here.

<img width="225" alt="Screenshot 2023-03-14 at 3 10 23 PM" src="https://user-images.githubusercontent.com/86495896/225153857-0440feaa-4381-431f-a78e-3df3735ea009.png">
<img width="324" alt="Screenshot 2023-03-14 at 3 14 33 PM" src="https://user-images.githubusercontent.com/86495896/225154322-0b4a3fe0-37fc-4e82-93df-7089b201071b.png">

**Comment by istarkov** [comment]
auto auto is default value for background-size, based on css spec. What should we put in inputs as initial values to show units.

**Comment by taylornowotny** [comment]
> auto auto is default value for background-size, based on css spec. What should we put in inputs as initial values to show units.

When value is Auto, show unitless unit. Auto is available in the unit menu. This is shown in the Size section docs in figma.
<img width="114" alt="Screenshot 2023-03-14 at 3 23 01 PM" src="https://user-images.githubusercontent.com/86495896/225155555-4e8a8af7-8430-44ad-91d4-31ec9e49c81e.png">

**Comment by taylornowotny** [comment]
<img width="802" alt="Screenshot 2023-03-14 at 3 26 58 PM" src="https://user-images.githubusercontent.com/86495896/225156154-6c58613d-f99a-4949-a2b3-fb1fa2ed705b.png">

**Comment by istarkov** [comment]
Moreover I fixed a month ago that in most such fields the only unitless value is 0
<img width="126" alt="image" src="https://user-images.githubusercontent.com/5077042/225156955-bd36889a-e0ec-4c5c-9958-39772a35790e.png">

**Comment by taylornowotny** [comment]
We have to show a unit for keyword values to indicate that the unit menu exists. Otherwise users won't see it. 

You are right that many of the inputs are incorrect in prod currently.

**Comment by taylornowotny** [comment]
One more thing - is a white background a Webstudio default or a CSS default? We don't use the "preset" label for CSS defaults. <img width="239" alt="Screenshot 2023-03-14 at 3 32 11 PM" src="https://user-images.githubusercontent.com/86495896/225157090-ef557e8f-4444-4181-b4f6-ce342d9d959c.png">

**Comment by istarkov** [comment]
White is for the Body only as it's set somewhere in our default styles. Its not on this Control to redefine existing styles.

Color dropdown has all css colors
<img width="259" alt="image" src="https://user-images.githubusercontent.com/5077042/225157419-b311409a-c692-4e20-88c3-d3fe02b51efe.png">

**Comment by taylornowotny** [comment]
Ok I will make separate issues for these.

**Comment by kof** [comment]
We need to make decision around keywords vs. units. Auto is a keyword px is a unit. While in a simplified way it makes sense to include Auto in the same dropdown for convenience, it would be inconsistent and we can't include all keywords in unit menu because these are sometimes a long list, so we kinda need to discuss this once again.

This decision has not been made yet. So right now the menu on the right only includes units and keywords are shown when you remove everything or when you start typing and autocomplete can match a keyword. 

Lets have a brainstorming session about this, its not a solved problem and its not as simple as just putting some special keywords into units menu.

**Comment by istarkov** [comment]
- [ ] - Focus should work inside layer items using arrows (left/right)
- [ ] - Between layers using (top/down)

**Comment by taylornowotny** [comment]
I made an update to the designs.

1. Section titles can now be used as property labels. ref:#1271
 Now, the Background section title represents the background CSS property. When a background is added, then the label in the Section Title should turn blue (local). 
2. CSS Value List Items will not have colored labels in the Background section
3. Renamed section from 'Backgrounds' to 'Background'
4. Updated docs

<img width="499" alt="Screenshot 2023-03-20 at 7 45 59 PM" src="https://user-images.githubusercontent.com/86495896/226506819-86eeca78-52f3-49c8-a985-8268244bd9e5.png">
